name: Configuration Fake Deploy Github Action

on: 
  push:
    branches:
      - main
      - master

jobs: 
  run-unit-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          java-version: 8
          distribution: 'adopt'
          cache: maven

      - name: Unit Tests
        run: mvn clean package

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with: 
          name: PathFinder
          path: PathFinder-${{ github.sha }}.jar
  
  fake-deploy:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps: 
      - name: Get the artifact
        uses: actions/download-artifact@master
        with:
          name: PathFinder
          
      - name: Fake deploy
        run: ls PathFinder*.jar
