name: Configuration Test And Coverage Github Action

on: 
  push:
    branches-ignore:
      - main
      - master
    pull_request:
      branches:
        - 'main'
        - 'develop'
        - 'release'

jobs: 
  run-all-tests:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with: 
          java-version: 1.8
          distribution: 'adopt'
      
      - name: Setup Maven
        uses: stCarolas/setup-maven@4.4
        with: 
          maven-version: 3.8.2

      - name: Run tests and Coverage
        run: mvn clean install
